### ISSUE TITLE
Test IE deduping for raw IE transactions

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-testing#130]
**What we're after:** 
We've made changes to the IE deduping work on the independent expenditures datatable and now need to test the changes that have been made. 

**Related issues:**
https://github.com/fecgov/fec-testing/issues/122

**Completion criteria:**
- [ ] Conduct testing and compile takeaways and recommendations for future changes

**Comment by JonellaCulmer** [comment]
**Test script:**
https://docs.google.com/document/d/122xp277PRUhjsGKBxl544n87VnxA1Jpz3XvqjjmD89U/edit#

**Notetaking spreadsheet:** https://docs.google.com/spreadsheets/d/1Z3T45hb1WAhD1zRL_fLXZlfQ9ApenTvgYE0OM0eLhaE/edit#gid=313597352

**Comment by JonellaCulmer** [comment]
*Mural with summary notes and groupings:*
https://app.mural.co/t/fec4461/m/fec4461/1586446837028/e881d609b6ac8992220ac46717d035e1fed52bae

### IE deduping
**Summary notes:**
- Users are still confused with the label language and understanding what version means, without reading the methodology.
     - Three of five tested suggested a name change to the filter
- Nearly all users went to the flyout panel to find version information, but one had trouble noticing the Current version listed in the flyout

**Takeaways:**
- Need to keep thinking of how to improve the filter for filtering out past versions.
     - Consider name suggestions from users: Current version (with an asterisk to explain further), Current, Latest available, Filter out duplicates

### Presidential map
**Summary notes:**
- Easily find the "all candidate figures" and figures of candidates at the nationwide view
- Understand the purpose of the map, although one user expressed not knowing when she would use it
- Able to find per state dollar figures by using the cursor
- Users went to features they were used to instead of looking for a map when looking for "high-level figures"
- Easily find other top figures on the right after selecting specific candidates
- Can glean trends after viewing the map
- Trouble using the state view, either with the clicking in and out of the feature, not noticing the figures on the left updating

**Takeaways:**
- Consider improvements to the drilldown to the state views that make it clear which dollar figures are specific to which state
     - Include: the breadcrumbs, clicking state to zoom in/out, interaction when dollar figures change

**Comment by JonellaCulmer** [comment]
Opened a ticket for the IE deduping work, here: https://github.com/fecgov/fec-cms/issues/3680

Tracking presidential map work in the moscow doc here: https://docs.google.com/document/d/1CH5-W6QzVF7Zve2P3ttVPK9gdfVNm_x5NBY4gXoV9vQ/edit#
