### ISSUE TITLE
Users may need more context for what they're seeing on advanced data pages

### ISSUE THREAD

**Issue by nickykrause** [fecgov/fec-testing#18]
## What research effort prompted this issue?
Usability testing of the homepage prototype, 12-1-2016, as seen in issue #17  

## Link/Screenshot of tested material
[Prototype link](https://gsa.invisionapp.com/share/2U9JSARKH#/screens)

## What happened?
One user was confused by the "Individual Contributions" data page, after clicking through to it from a link to "individual contributions" on the homepage.

Details:
Although the user immediately found a link for her task on the homepage (“Learn who’s donating to candidates and committees”), she was confused by the page she landed on. She felt that she was in the right place, but didn’t immediately see a way to actually look someone up, which is what she thought she’d see. She was also confused by the data that was already showing. Here's what she saw:

<img width="1276" alt="screen shot 2016-12-02 at 2 58 58 pm" src="https://cloud.githubusercontent.com/assets/1450173/20850268/ec6f5108-b89f-11e6-8f29-75c7b789856e.png">

Quote: 
> “I have no idea what I’m looking at on this page; there’s nothing that explains how this is ordered. What is this information that’s already populated here? Why is that there? I don’t see how I can look someone up by name, which is what I thought I’d be able to do.”

## Analysis
@noahmanger pointed out that this has come up before with users, and @jenniferthibault elaborated: 
> We are making the data tables a priority link, but not providing the context needed for people who don't know what they're looking at

**Comment by jenniferthibault** [comment]
An update on some changes we've made to address this issue:

Since: 
- Real estate on the data table pages themselves is already crowded and limited
- The mega mega menu surfaced too much information, and didn't prioritize enough, and
- The advanced data page was being underused, while more data sets were becoming available

We:
- Prioritized and reduced the mega menu to direct people to the Advanced data page in order to get to the data tables
- Restructured the advanced data pages to better associate content & intro with the available data sets

The current hypothesis is that we think users can access context about the different data sets through the new layout before clicking into the data tables:

<img width="1436" alt="screen shot 2017-04-19 at 10 35 39 pm" src="https://cloud.githubusercontent.com/assets/11636908/25211254/5394a346-2552-11e7-903c-727452a6193c.png">
<img width="1436" alt="screen shot 2017-04-19 at 10 35 55 pm" src="https://cloud.githubusercontent.com/assets/11636908/25211255/53ad13fe-2552-11e7-9b10-40eacc0b6d45.png">

**Comment by JonellaCulmer** [comment]
This data table has since been updated to make it easier for users to search by contributor name. So this ticket may now be moot. Closing.
