### ISSUE TITLE
User request: Make committee pages easy to print

### ISSUE THREAD

**Issue by nickykrause** [fecgov/fec-testing#50]
While testing [this script](https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Test-Script-3-31-17-Committee.md), one user commented that he would like an easy way to print committee pages. 

His reasoning was that he consults for candidates who are running campaigns, and he likes to be able to sit down with them and talk about how they are doing compared to their competitors. In preparation for those meetings, he will often print information about various committees (and candidates) for review while traveling, and for use in facilitating conversations with candidates.

**Comment by jenniferthibault** [comment]
@nickykrause this one is interesting! Do you remember the circumstances around the request? I.e.,
- was he disappointed with the existing print formatting, (did he try `File` > `print` and was disappointed with the results)? or 
- did he think the page wasn't printable because there is no specific call out (was he expecting distinct `print` feature on the page, like a button or something)?

**Comment by nickykrause** [comment]
My recollection is that he assumed there wasn't a way to print because of the lack of a print button, but I'm not entirely sure. He is a very responsive user so I'll send him an email and see if he could clarify the request!

**Comment by nickykrause** [comment]
He said:

> The [print] layout [on the beta site] is definitely cleaner (I certainly don't get part of the page architecture printing over the data [like I did on the old site], which is a big improvement), but I like the pie chart graphic, and it doesn't appear to generate for the financial summary pages in the beta version.
