### ISSUE TITLE
Test candidate reporting examples

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-testing#76]
Candidate reporting examples will be finished soon, this is the ticket: https://github.com/18F/fec-cms/issues/1170

We need to be able to test the functionality of the candidate reporting examples and if the users are able to use the examples to complete tasks. Usability script and ideas to follow.

**Comment by llienfec** [comment]
@patphongs We talked about a few options for potential A/B testing at the Chicago conference.  If testing this type info still sounds good, the reporting examples content & design team can come up with a few suggestions for scripts/visuals if you don't mind reviewing and tweaking them.  We're happy to make tests in whatever format is easiest for you. 

Here's what we've been discussing so far:

### A/B testing for reporting examples

 - Highlighting form fields - @jenniferthibault designed a great highlighting option so that we can draw users' attention to particular parts of a form, depending on what the reporting example is.  Our general research question is whether or not it's helpful to highlight all of the form's fields when we're not talking about a specific part of the form.
 - Plural vs singular reporting example names - Each page is labeled "How to report." After that, we add a title based on the reporting example.  @jameshupp suggested we test to see if singular or plural titles work better for users.
> A contribution from an individual vs Contributions from individuals.  
> A contribution through a conduit vs Contributions through a conduit vs Contributions through conduits

cc: @rhoughfec, @jjones0618

**Comment by llienfec** [comment]
Planning to include initial reporting example testing in the Chicago Conference testing.  

Instead of A/B testing, we're testing:
- Highlighting form fields - testing image of fully highlighted form 
![image](https://user-images.githubusercontent.com/22914750/29731487-9f0c1c7c-89b2-11e7-8948-e58c19cc5a80.png)

- Plural vs singular reporting names - testing image plural names to see if committees can find an example based on a scenario we give them.
![image](https://user-images.githubusercontent.com/22914750/29731495-a46b4b66-89b2-11e7-9873-5622b87df61e.png)

**Comment by llienfec** [comment]
### Initial findings from Chicago conference testing
We tested two main questions regarding the reporting examples:
- Are plural names confusing? -  Users did not appear to be confused.  Content team will move forward with using plural names for reporting examples.
-  Is highlighting each form field effective? - Users thought it was clear which fields needed to be filled in.  Content team will move forward with the proposed highlighting style and frequency.

### Incidential findings
Users gave us additional information to consider as we continue to build reporting examples:
- Some users get confused over terminology #79 
- Some users wanted a filtering mechanism to help them get to the right reporting example #80 
- Users were confused by similar names in reporting examples #81 

@patphongs has a great document of all findings from all of the conference research as well.
cc: @rhoughfec @jameshupp @jenniferthibault @jjones0618

**Comment by jenniferthibault** [comment]
This is a great writeup & issue thread, thanks @llienfec !
