### ISSUE TITLE
Some users wanted a filtering mechanism for reporting examples

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-testing#80]
In the Chicago reporting example testing, one user wanted to drill down into more generic categories to answer the questions we asked about which example they would choose to help them report a contribution from a person and donating to charity.

Another user noticed something similar where they wanted groupings within categories based on what’s more frequently used. Finding subsets of specific contributions or disbursements when linking to examples.

### Moving forward
1.  MVP - content makers will work on a couple of different ways to break down the information.
1.  Will need to test the published product to see if the groupings make sense to users.

**Comment by JonellaCulmer** [comment]
In order to help with the groupings and category development we can conduct a card sorting exercise with users, either digitally, or at the upcoming DC Conference. At the DC conference we would bring cards listing out the different categories and ask participants to group the topics into categories that make the most sense to them. We can later review the results as a group.

This will give us an opportunity to validate any groupings we already have, or help us in the right direction.
