### ISSUE TITLE
Contact FEC

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-testing#89]
# Testing ideas
Several fec-testing issues/testing ideas have been logged regarding the findability and usability of the FEC contact page. This issue consolidates them.

Presently the page can be found by going to the FEC.gov footer found on all pages and clicking ‘Contact’. With the introduction of the About Page, some testing has revealed that users want to now go to the About page dropdown to find the Contact page as well. (#84). 

Testing Ideas for the Contact Page and other associated links:
- We want to be sure that users are able to find the RAD form, located on the contact page, and that they know how it works, specifically the feature that allows them to find their RAD analyst. (#53)
     - Users have attempted to search for the committee to find this information. Users have attempted to find in the ‘About’ section of the committee’s profile page. (#87)
     - Want to make it easy for committee’s to locate their analyst’s contact information, not a user simply looking for information about a committee. 
- The ability for users to find out about public appearances on the Contact page. Lots of additions to the page may have impacted how users contact the agency. (#75)
- Contact page contents in general, departments and contact information included (#85). Does the organization of the page help or hinder page usability?

# Story
Melanie is a mother of a young child and professional filer who maintains the reports of multiple clients, so she tries to maintain a good work-life balance. She uses the website to find answers when she needs research. However, if she can’t find information quickly, she’d rather call the FEC to answer to her question and needs to be able to find contact information for different FEC departments. 

# Hypothesis
We hypothesize that users who are looking for the contact form will try one of two ways to access the form, either through the page footer, or through the About page. 
Test Questions to ask
- ***How long the user has been in the field/industry?***
- ***What is their role? Consultant, attorney, treasurer, etc***
- Are users able to successfully find the contacts they need?
- Which departments do users contact the most frequently?

**Comment by JonellaCulmer** [comment]
Testing Script

# October 5, 2017 Test Script
## Quick connection links:
> https://plus.google.com/hangouts/_/calendar/cHBob25nc3ZpcmFqYXRpQGZlYy5nb3Y.09e85ijoun7enj386llutc41m0?authuser=0
> https://appear.in/fec-website-testing?skipCamPrimer

## Features tested this week:
### Contact your analyst
Navigating to the ‘Contact your analyst’ feature
Ability to find their committee’s analyst
### Contact page
Navigating to contact page from the home page
Contact page clarity
Ability to find out about public appearances
## Introduction script:
Hi, I'm ___, and I'm working on the Federal Election Commission website redesign, and we'd like to get your feedback on some new content we're adding. Before we start, I want to make it clear that we're testing the designs, not you. You can't do anything wrong here - all answers are the right answers.

Although it may seem a little weird, I'm going to ask you to think out loud as much as possible as you look at the designs. Describe what you're looking at, what you're trying to do, and what you're thinking. This will be a huge help to us.

Finally, please don't worry that you're going to hurt our feelings. We're doing this to improve the site, so we need to hear your honest reactions. Sound good?
[wait for user confirmation; clarify things if user asks questions]
(credit: Krug)
## Introduction questions:
Before we take a look at the website, I’d first like to ask a few things:

What is your background?
Do you visit the FEC website often?
When you come to the FEC’s website, what kinds of information are you looking for?
## Contact page questions
**Task 1:** When you have a question for the FEC, what would you do?
*If they don’t interact with the site, ask them Task number 2. If they do, skip to number 3.*

**Task 2:** Using our website, how would you do that?
**Task 3:** If you want someone to come talk to your group, what email would you use?
**Task 4:** You’re looking for a registered committee, but you can’t find it on our website, who would you reach out in order to find the committee?
*Prompt them to tell us why they selected that department over another. “Why did you choose that department?” 

When you speak with someone at the FEC, who do you speak with most frequently?
Do you have any general impressions of this page?
## Contact your Analyst questions
**Task 5:** You have a question about your committee and want to speak to your analyst. How would you find his or her information?
**Task 6:** Instead of calling your analyst, you’d like to send them a message. How would you do that?
Do you have any general impressions of this page?
## General questions
Those are all the questions I had!

Are there any questions you wish I asked you but didn’t?
Did you have any final thoughts you'd like to share?
Do you have any questions for me?

**Comment by JonellaCulmer** [comment]
The contact information was also tested at the DC conference. Script below:

# November 14-15, 2017 Test Script
###  Quick connection links:
**Notetaking Link:**
https://drive.google.com/drive/folders/1OrXQK3NSw36CZJy_8JRdVwbuGYQ9bHrq 
**Mural board:**
https://app.mural.ly/t/gsa6/m/gsa6/1510940922920/0c85bbccf06947c251a631d778eab958af4eb72c 
## Features to test:
### Candidates and Committees landing page 
Tested on dev: https://fec-dev-proxy.app.cloud.gov/ 
Landing page findability
Usability of the landing page
## Contact FEC 
Navigating to the ‘Contact’ page
Navigating to the ‘Contact your analyst’ form
## Candidate reporting examples
Findability of the reporting examples; naming logic
## AO/MUR boolean search
Usability of ‘More keyword options’
## Introduction script:
*Start by asking how much time they have. That will help gauge how many mini-tests you can conduct. It will also reflect well on us, having taken the time to ask and respecting their time.

Hi, I'm ___, and I'm working on the Federal Election Commission website redesign, and we'd like to get some quick feedback on new features and content we're adding. Before we start, I want to make it clear that we're testing the designs, not you. You can't do anything wrong here and all your answers will be the right ones. Also, please don't worry that you're going to hurt our feelings. We're doing this to improve the site, so we need to hear your honest reactions.
Although it may seem a little weird, I'm going to ask you to think out loud as much as possible as you look at the designs. Describe what you're looking at, what you're trying to do, and what you're thinking. This will be a huge help to us. Sound good?
[wait for user confirmation; clarify things if user asks questions]
(credit: Krug)
## Introduction questions:
What is your job in campaign finance?
How long have you been in the industry?
Topic questions:

### New H4CC landing page
This test needs to be done on dev. Have user go to: https://fec-dev-proxy.app.cloud.gov/ 

Mini-test 1: Landing page findability (starting on website homepage)
You received a contribution that is excessive. What steps would you take to handle this?
Mini-test 2: Usability of the landing page (starting on landing page)
You’ve just started on a new campaign, and want to stay on top of when reports are due. Can you try to find that information based on what you see here?
Your committee received a strange contribution, and you want to know whether is it permissible. Can you find a page on this website that tells you whether or not this is possible? 



### Contact FEC
Mini-test 1: Navigation to contact page (starting on homepage)
You can’t remember whether green card holders can make contributions and want to call someone at the FEC to check. Can you try to find a page on the website with FEC phone numbers?
Mini-test 2: Navigation to RAD contact form (if already on contact page from last test, start there, otherwise, start from homepage)
We now have tool to send your analyst a message should you need to contact them. How would you find that form to send your analyst a message?

### Candidate Reporting Examples (for campaign filers)
These are the names of different types of receipts and expenditures and clicking on one will show you how to report them. 
Mini-test: Topic naming logic (start from homepage)
A family friend paid for a tent at one of your candidate’s outdoor events. Which, if any, of these would you look at to learn how to report that information?
Do you notice anything missing?

### AO/MUR Boolean Search (for lawyers if you see them)
Mini-test: Usability of more keyword options (start from AO search)
Using what you see here, how would you conduct a more advanced search?

## Closing questions:
Are there any questions you wish I asked you but didn’t?
Any other feedback to share?
Do you have any questions for me?

**Comment by patphongs** [comment]
Closing this issue as this has been tested in the past. We don't need to do additional testing at this point. Will revisit if that changes.
